CREATE TABLE IF NOT EXISTS Users (
	id INT(6) AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	email VARCHAR(50),
	password CHAR(60)
);

CREATE TABLE IF NOT EXISTS Links (
	id INT(6) AUTO_INCREMENT PRIMARY KEY,
	user_id INT(6),
	url TEXT NOT NULL,
	shortened VARCHAR(6) NOT NULL
)